export const projectsData = [
    {
        title: 'ERP APP',
        description: "Cette application est un ERP personnalisée en fonction des besoins spécifiques de une entreprise et offre des fonctionnalités telles que la gestion des stocks(Suivi des niveaux de stocks, des commandes d'achat et de la réception de marchandises), la gestion commerciale(Suivi des ventes, des devis et des factures) et la gestion comptable et la gestion du personnel.",
        miniature: '/images/1.png',
        images: ['/images/1.png',],
        tags: ['PostgresSQL', 'Express', 'React', 'Node'],
        visit: 'https://medequip.app',
        source: '',
        id: 0,
    },
    {
        title: 'E-School',
        description: "Cette application est une plateforme personnalisée qui comprend des fonctionnalités telles que la gestion des étudiants(Suivi des enregistrements, des inscriptions, des listes de classe, presences), la gestion comptable(recouvrement, la relance, depense, tresorie) et données analytiques.",
        miniature: '/images/2.png',
        images: ['/images/2.png'],
        tags: ['Symfony', 'MySQL', 'PHP'],
        visit: 'https://ayenouan.itwebson.ci/',
        source: '',
        id: 1,
    },
    {
        title: 'E-Market APP',
        description: "Cette application est un ERP basé sur une API déjà existante plus axé sur la gestion d'un super marché.",
        miniature: '/images/3.png',
        images: ['/images/3.png',],
        tags: ['React', 'Express', 'Barcode', 'PostgresSQL', 'Node'],
        visit: 'https://github.com/IT-Webson/SocialMarketFrontend',
        source: 'https://github.com/IT-Webson/SocialMarketFrontend',
        id: 2,
    },
    {
        title: 'Find Job',
        description: "Cette application est une plateforme de recherche d'emploi. Elle dispose de plusieurs fonctionnalités liées a la recherche d'emploi.",
        miniature: '/images/4.png',
        images: ['/images/4.png',],
        tags: ['HTML', 'Blade', 'Laravel', 'PHP'],
        visit: 'https://github.com/niikiies05/FindJob',
        source: 'https://github.com/niikiies05/FindJob',
        id: 3,
    },
    // {
    //   title: 'Univ Rec',
    //   description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    //   miniature: '/images/4.jpg',
    //   images: ['/images/4.jpg'],
    //   tags: ['Blade', 'Laravel', 'PHP'],
    //   visit: 'https://google.com',
    //   source: 'https://google.com',
    //   id: 4,
    // },
    // Ajoutez d'autres projets ici
];