export const projectsData = [
    {
        title: 'FYLE CARE',
        description: "Solution de gestion en temps réel dans le domaine de l''assurance santé et des mutuelles de santé est conçue pour englober l'ensemble du réseau de soins et gérer l'intégralité de l'activité de production et prestation. Elle débute par l'immatriculation des bénéficiaires et s'étend jusqu'au règlement des factures des prestataires médicaux. Cette application est constitué de (8) huit Web pour les différents réseaux de soins, Médecin conseil & Siège (Web), Centre de Santé & Laboratoire (Web & Mobile), Assuré & Ayant droits (Web & Mobile), Pharmacie (Web & Mobile), Cabinet Dentaire (Web), Laboratoire & Centre d'imagerie (Web), Centre Optique (Web) ",
        miniature: '/images/fyle_care_bo_img1.PNG',
        images: [
            '/images/fyle_care_hopital_img1.PNG',
            '/images/fyle_care_bo_img1.PNG',
            '/images/fyle_care_hopital_img2.PNG',
            '/images/fyle_care_medco_img1.PNG',
            '/images/fyle_care_pharmacie_img1.PNG',
        ],
        tags: ['MySQL', 'Laravel', 'React', 'Flutter'],
        // visit: 'https://medequip.app',
        // source: '',
        id: 1,
    },
    {
        title: 'EGOUEXPERT',
        description: " solution complète destinée aux cabinets d'audit, facilitant le contrôle et le suivi des missions d'audit. Elle permet de gérer les dossiers des clients audités, les équipes de mission, et le traitement des dossiers. Elle inclut des fonctionnalités telles que l'importation, la génération, et la comparaison de fichiers, ainsi que la gestion des droits d'accès et du workflow. De plus, elle simplifie la clôture et l'ouverture des exercices. Aussi elle inclut un back office de gestion assurant une gestion efficace des cabinets d'audit clients, ainsi qu'une application mobile pour le suivi des mission d'audit",
        miniature: '/images/egouexpert_img2.PNG',
        images: [
            '/images/egouexpert_img1.PNG',
            '/images/egouexpert_img2.PNG',
            '/images/egouexpert_bo_img1.PNG',
        ],
        tags: ['MySQL', 'NodeJs', 'React', 'Flutter'],
        // visit: 'https://medequip.app',
        // source: '',
        id: 1,
    },
    {
        title: 'ERP APP',
        description: "Cette application est un ERP personnalisée en fonction des besoins spécifiques de une entreprise et offre des fonctionnalités telles que la gestion des stocks(Suivi des niveaux de stocks, des commandes d'achat et de la réception de marchandises), la gestion commerciale(Suivi des ventes, des devis et des factures) et la gestion comptable et la gestion du personnel.",
        miniature: '/images/1.png',
        images: ['/images/1.png',],
        tags: ['PostgresSQL', 'Express', 'React', 'Node'],
        visit: 'https://medequip.app',
        source: '',
        id: 4,
    },
    {
        title: 'E-School',
        description: "Cette application est une plateforme personnalisée qui comprend des fonctionnalités telles que la gestion des étudiants(Suivi des enregistrements, des inscriptions, des listes de classe, presences), la gestion comptable(recouvrement, la relance, depense, tresorie) et données analytiques.",
        miniature: '/images/2.png',
        images: ['/images/2.png'],
        tags: ['Symfony', 'MySQL', 'PHP'],
        visit: 'https://ayenouan.itwebson.ci/',
        source: '',
        id: 5,
    },
    {
        title: 'E-Market APP',
        description: "Cette application est un ERP basé sur une API déjà existante plus axé sur la gestion d'un super marché.",
        miniature: '/images/3.png',
        images: ['/images/3.png',],
        tags: ['React', 'Express', 'Barcode', 'PostgresSQL', 'Node'],
        visit: 'https://github.com/IT-Webson/SocialMarketFrontend',
        source: 'https://github.com/IT-Webson/SocialMarketFrontend',
        id: 6,
    },
    {
        title: 'Find Job',
        description: "Cette application est une plateforme de recherche d'emploi. Elle dispose de plusieurs fonctionnalités liées a la recherche d'emploi.",
        miniature: '/images/4.png',
        images: ['/images/4.png',],
        tags: ['HTML', 'Blade', 'Laravel', 'PHP'],
        visit: 'https://github.com/niikiies05/FindJob',
        source: 'https://github.com/niikiies05/FindJob',
        id: 7,
    },
    // Ajoutez d'autres projets ici
];